spring:
  application:
    name: gateway
  config:
    import: "optional:consul:"
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: 8500
      discovery:
        service-name: gateway
    gateway:
      mvc:
        routes:
          - id: accounts-service
            uri: lb://accounts-service
            predicates:
              - Path=/api/v1/accounts/**
          - id: cash-service
            uri: lb://cash-service
            predicates:
              - Path=/api/v1/cash/**
          - id: transfer-service
            uri: lb://transfer-service
            predicates:
              - Path=/api/v1/transfers/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://keycloak:8180/realms/bank}

server:
  port: 8090
